/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ordering_system_MainActivity */

#ifndef _Included_com_example_ordering_system_MainActivity
#define _Included_com_example_ordering_system_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ordering_system_MainActivity
 * Method:    Print7Segment
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_ordering_1system_MainActivity_Print7Segment
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_example_ordering_system_MainActivity
 * Method:    PrintLed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_ordering_1system_MainActivity_PrintLed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_ordering_system_MainActivity
 * Method:    GetRes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ordering_1system_MainActivity_GetRes
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ordering_system_MainActivity
 * Method:    GetTouch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ordering_1system_MainActivity_GetTouch
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
